import dotenv from 'dotenv';
dotenv.config();

const constants = Object.freeze({
    CONST_APP_VERSION: process.env.APP_VERSION,
    CONST_DB_URL: process.env.MONGO_URI,
    CONST_GEN_SALT: 10,

    CONST_RESP_LANG_COLLECTION: ["en"],

    // API Response code
    CONST_RESP_CODE_OK: 200,
    CONST_RESP_CODE_CREATED: 201,
    CONST_RESP_CODE_CONTENT_NOT_FOUND: 204,
    CONST_RESP_CODE_DATA_NOT_MODIFIED: 304,
    CONST_RESP_CODE_BAD_REQUEST: 400,
    CONST_RESP_CODE_UNAUTHORIZED: 401,
    CONST_RESP_CODE_NOT_FOUND: 404,
    CONST_RESP_CODE_NOT_ACCEPT: 406,
    CONST_RESP_CODE_INTERNAL_SERVER_ERROR: 500,
});

export default constants;